"""added_conversation_data

Revision ID: 7c5f2ef2a6c2
Revises: c3b36db87a15
Create Date: 2025-12-30 01:00:13.910453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5f2ef2a6c2'
down_revision = 'c3b36db87a15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('conversation_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'conversation_data')
    # ### end Alembic commands ###

